spring:
  profiles:
    include:
      - db
      - aws
      - secret

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  jpa:
    hibernate:
      ddl-auto: none #update #none #create
    show-sql: true

  datasource:
    data: classpath*:db/data.sql

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    root: info
