spring:
  profiles:
    include:
      - db
      - aws
      - secret

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    data: classpath*:db/data.sql

logging:
  level:
    root: info
